### PR TITLE
Travis reformat js

### PR DESCRIPTION
**Pull request by Ichag**
All js files have been reformatted according to prettier introduced in https://github.com/bolt/four/pull/128
To separate the task of integrating prettier and reformatting all JS files this PR was created after #128.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Our code style (PHP-CS-fixer) for PHP is configured for 4 spaces, and single quotes `'` instead of double `"`. 

Maybe we should stick with 2 spaces in JS, because i think that's more common, but i _do_ think we should use single quotes, for consistency.

**Comment by bobdenotter** [comment]
@Ichag @jackiboy Any input? Otherwise I'm going to set the indentation to "Three tabs" 😜

**Comment by Ichag** [comment]
I will change the prettier configuration to match the php style conventions

**Comment by bobdenotter** [comment]
@Ichag Cool! After you've done so, we can rebase and get it merged in. 👍

**Comment by JarJak** [comment]
@marcingajda have a look on this one

**Comment by marcingajda** [comment]
@JarJak A lot of conflicts. I will fix the violations from scratch using using the new code a copy the travis configs from here. Also we decide to use rules popular amongst the JS community instead of looking what is popular in PHP world.

**Comment by JarJak** [comment]
Fixed in #280

**Pull request closed without merging**
