### PR TITLE
ECS Fixes

### PR DESCRIPTION
**Pull request by JarJak**
Not everything is fixed yet.

Includes config from #142

### CODE REVIEW

**Comment by JarJak** [comment]
TBD: If we want a space after exclamation mark.

**Comment by bobdenotter** [comment]
I see it removes a lot of `@param` and `@returns` from the docblocks, in favor of Type Hinting.. I think it's fine, but doesn't this leave people out in the cold who don't have PHPstorm or another "modern" IDE?

**Comment by bobdenotter** [comment]
> TBD: If we want a space after each exclamation mark.

I'm fine with or without. This is one of these things that are easy to just adopt, and go with the flow.

**Comment by bobdenotter** [comment]
> Also I don't know which IDE reads phpdoc, but skips type hints?

Neither do I, was just wondering out loud. Did a quick test and both PHPstorm and VSCode do it, so IMHO that is a good baseline: Both "professional" developers who use paid tools, as well as novices on VScode will be able to see the hints.. 

Let's roll with this! Should I merge #142 first, and then work on this until it's green?

**Comment by JarJak** [comment]
Yes, let's merge #142 first (if it's config is fine for everyone). Additionally Travis config needs to be tweaked a bit.

**Comment by JarJak** [comment]
37 errors ECS errors and 33 PHPStan errors. Not bad ;)

**Pull request merged**
