### PR TITLE
Improve API Response and remove Magic from Content

### LINKED ISSUE #38: API: Flesh out API endpoints for frontend

### LINKED ISSUE #151: MagicContentTrait DX improvements
Splitted from https://github.com/bolt/four/pull/148

- [x] I really don't like all those "magic" methods in ContentMagicTrait. Can we at least rename them to be less magical? :)
- [x] if we could make $this->fields a name-indexed array, using this method be much faster (simple isset instead of foreaching).
- [x] rename to get to getField, has to hasField

### LINKED ISSUE #182: Make "Content" less magical

### LINKED ISSUE #271: Remove jsonrecords Twig helper
Content serialization should be done with Serializable or JsonSerializable interface. JSONed Content should look the same in Twig as well as in API response. 

So:
```twig
{{ jsonrecords(records) }}
```
Should be replaced with:
```twig
{{ records|json_encode }}
```

### PR DESCRIPTION
**Pull request by JarJak**
Provides changes described here: https://github.com/bolt/four/issues/151#issuecomment-456311890

I've probably broke some Vue components here, @marcingajda please help :)

RFC: `{{ record|excerpt }}` vs `{{ record | excerpt }}`. Out frontend devs prefer the latter but I want to know your opinion too. @xiao @anketwokings @sbonardt @jadwigo
 
Closes #38 
Closes #151
Closes #182
Closes #271

### CODE REVIEW

**Comment by sbonardt** [comment]
Hi @JarJak 

What's the rationale behind {{ record | excerpt }} ? And why do your frontend dev's prefer that RFC?

**Comment by JarJak** [comment]
@sbonardt I guess it is more readable with spaces. On the other hand Twig docs doesn't recommend using spaces.

**Comment by sbonardt** [comment]
@JarJak Ah, ok. Then I oppose the RFC. 😄 I like to stick to the conventions/recommendations

**Comment by xiaohutai** [comment]
I prefer `foo|filter` without the spaces:

- `foo | bar` looks like two separate variables (compare with `foo & bar`, and `foo || bar`).
- I also wouldn't put places around `foo . bar` (weak argument as it's not really the same thing, but still).
- Twig docs also do it without spaces.
- If we would do it, we also need to re-write all (upcoming) Bolt docs to do that too? I feel there will be a gap between Twig docs and Bolt docs.

**Comment by JarJak** [comment]
Ok then, I will revert filters to not use spaces.

**Comment by JarJak** [comment]
Finally green :D

**Pull request merged**
